// src/App.tsx
import React from 'react'
import {BrowserRouter as Router, Link} from 'react-router-dom'
import RouterConfig from './router/RouterConfig'

function App() {
  return (
    <Router>
      <div>
        <nav>
          <ul>
            <li>
              <Link to="/public">Public</Link>
            </li>
            <li>
              <Link to="/application">Application</Link>
            </li>
            <li>
              <Link to="/job">Job</Link>
            </li>
            <li>
              <Link to="/user">User</Link>
            </li>
          </ul>
        </nav>

        <RouterConfig/>
      </div>
    </Router>
  )
}

export default App

// src/App.vue
<template>
    <div id="app">
        <div id="nav">
            <router-link to="/">Public</router-link>|
            <router-link to="/application">Application</router-link>|
            <router-link to="/job">Job</router-link>|
            <router-link to="/user">User</router-link>
        </div>
        <router-view/>
    </div>
</template>

<style lang="scss"></style>
